version: '3.8'  # It's good practice to specify the version of the Docker Compose file format

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  sql-data:
